MODEL_INFO = {
    'gpt2': {
        'model_name': 'openai-community/gpt2',
        'num_layers': 12,
        'num_heads': 12},
    'gpt2-medium': {
        'model_name': 'openai-community/gpt2-medium',
        'num_layers': 24,
        'num_heads': 16},
    'gpt2-large': {
        'model_name': 'openai-community/gpt2-large',
        'num_layers': 36,
        'num_heads': 20},
    'gpt2-xl': {
        'model_name': 'openai-community/gpt2-xl',
        'num_layers': 48,
        'num_heads': 25},
    'qwen2.5_0.5b': {
        'model_name': 'Qwen/Qwen2.5-0.5B',
        'num_layers': 24,
        'num_heads': 16},
    'qwen2.5_3b': {
        'model_name': 'Qwen/Qwen2.5-3B',
        'num_layers': 24,
        'num_heads': 16},
    'qwen2.5_7b': {
        'model_name': 'Qwen/Qwen2.5-7B',
        'num_layers': 24,
        'num_heads': 16},
}