MODEL_INFO = {
    'gpt2': {
        'model_name': 'openai-community/gpt2',
        'num_layers': 12,
        'num_heads': 12,
        'attn_implementation': 'eager',
        'eval_hidden_states': True,
        'max_batch_size': 48,
        'dtype': 'fp32'},
    'gpt2-medium': {
        'model_name': 'openai-community/gpt2-medium',
        'num_layers': 24,
        'num_heads': 16,
        'attn_implementation': 'eager',
        'eval_hidden_states': True,
        'max_batch_size': 24,
        'dtype': 'fp16'},
    'gpt2-large': {
        'model_name': 'openai-community/gpt2-large',
        'num_layers': 36,
        'num_heads': 20,
        'attn_implementation': 'eager',
        'eval_hidden_states': True,
        'max_batch_size': 8,
        'dtype': 'fp16'},
    'gpt2-xl': {
        'model_name': 'openai-community/gpt2-xl',
        'num_layers': 48,
        'num_heads': 25,
        'attn_implementation': 'eager',
'eval_hidden_states': True,
        'max_batch_size': 2,
        'dtype': 'fp16'},
    'qwen2.5_0.5b': {
        'model_name': 'Qwen/Qwen2.5-0.5B',
        'num_layers': 24,
        'num_heads': 14,
        'attn_implementation': 'eager',
        'eval_hidden_states': True,
        'max_batch_size': 32,
        'dtype': 'fp16'},
    'qwen2.5_1.5b': {
        'model_name': 'Qwen/Qwen2.5-1.5B',
        'num_layers': 28,
        'num_heads': 12,
        'attn_implementation': 'eager',
        'eval_hidden_states': True,
        'max_batch_size': 2,
        'dtype': 'fp16'},
    # Current 3b has bug
    'qwen2.5_3b': {
        'model_name': 'Qwen/Qwen2.5-3B',
        'num_layers': 36,
        'num_heads': 16,
        'attn_implementation': 'eager',
        'eval_hidden_states': False,
        'max_batch_size': 2,
        'dtype': 'fp16'},
    'qwen2.5_7b': {
        'model_name': 'Qwen/Qwen2.5-7B',
        'num_layers': 28,
        'num_heads': 28,
        'attn_implementation': 'eager',
        'eval_hidden_states': True,
        'max_batch_size': 8,
        'dtype': 'fp16'},
    'qwen2.5_14b': {
        'model_name': 'Qwen/Qwen2.5-14B',
        'num_layers': 48,
        'num_heads': 40,
        'attn_implementation': 'eager',
        'eval_hidden_states': False,
        'max_batch_size': 4,
        'dtype': 'fp16',
    },
    'qwen2.5_32b': {
        'model_name': 'Qwen/Qwen2.5-32B',
        'num_layers': 64,
        'num_heads': 40,
        'attn_implementation': 'eager',
        'eval_hidden_states': False,
        'max_batch_size': 1,
        'dtype': 'fp16',
    },
    'qwen2.5_72b': {
        'model_name': 'Qwen/Qwen2.5-72B',
        'num_layers': 80,
        'num_heads': 64,
        'attn_implementation': 'eager',
        'eval_hidden_states': False,
        'max_batch_size': 1,
        'dtype': 'fp16',
    }
}

# Models to run in the cross-model experiment (all that fit on an RTX 3050 4GB).
CROSS_MODEL_MODELS = ['gpt2', 'gpt2-medium', 'qwen2.5_0.5b',
                      'gpt2-large', 'qwen2.5_1.5b', 'gpt2-xl']
